hotel_homepage:
    path:     /
    defaults: { _controller: HotelBundle:Default:index }

hotel_homepage_backend:
    path:     /backend
    defaults: { _controller: HotelBundle:Default:backend }

#pagina publica

hotel_page_nosaltres:
    path:     /sobrelhotel
    defaults: { _controller: HotelBundle:Default:nosaltres }

hotel_page_serveis:
    path:     /serveis
    defaults: { _controller: HotelBundle:Default:serveis }

hotel_page_contacte:
    path:     /contacte
    defaults: { _controller: HotelBundle:Default:contacte }
