hotel_bundle_admintasca_homepage:
    path:     /
    defaults: { _controller: HotelBundleTascaBundle:AdministrarTasca:index }

hotel_bundle_admintasca_addTasca:
    path:     /add/Tasca
    defaults: { _controller: HotelBundleTascaBundle:AdministrarTasca:addTasca }

hotel_bundle_admintasca_editarTasca:
    path:     /edit/Tasca/{id}
    defaults: { _controller: HotelBundleTascaBundle:AdministrarTasca:editTasca }

hotel_bundle_admintasca_eliminarTasca:
    path:     /deleteTipusTasca/{id}
    defaults: { _controller: HotelBundleTascaBundle:AdministrarTasca:deleteTasca }

    #Tipus Tasca
hotel_bundle_tasca_homepage:
    path:     /tipusTasca
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:index }

hotel_bundle_tasca_addTipusTasca:
    path:     /addTipusTasca
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:addTipusTasca }

hotel_bundle_tasca_editarTipusTasca:
    path:     /edit/TipusTasca/{id}
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:editTipusTasca }

hotel_bundle_tasca_eliminarTipusTasca:
    path:     /deleteTipusTasca/{id}
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:deleteTipusTasca }

