hotel_bundle_tasca_homepage:
    path:     /
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:index }

hotel_bundle_tasca_addTipusTasca:
    path:     /addTipusTasca
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:addTipusTasca }

hotel_bundle_tasca_editarTipusTasca:
    path:     /edit/TipusTasca/{id}
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:editarTipusTasca }

hotel_bundle_tasca_eliminarTipusTasca:
    path:     /deleteTipusTasca/{id}
    defaults: { _controller: HotelBundleTascaBundle:TipusTasca:deleteTipusTasca }
