hotel_bundle_usuari:
    resource: "@HotelBundleUsuariBundle/Resources/config/routing.yml"
    prefix:   /backend/usuari

hotel_bundle_tasca:
    resource: "@HotelBundleTascaBundle/Resources/config/routing.yml"
    prefix:   /backend/tasca

hotel_bundle_admin_tasca:
    resource: "@HotelBundleTascaBundle/Resources/config/adminRouting.yml"
    prefix:   /backend/admin/tasca

hotel_bundle_admin:
    resource: "@HotelBundleAdminBundle/Resources/config/routing.yml"
    prefix:   /backend/admin

hotel_bundle_reserva:
    resource: "@HotelBundleReservaBundle/Resources/config/routing.yml"
    prefix:   /reserva

hotel_bundle_treballador_reserva:
    resource: "@HotelBundleReservaBundle/Resources/config/treballadorRouting.yml"
    prefix:   /backend/reserva

hotel_bundle_admin_reserva:
    resource: "@HotelBundleReservaBundle/Resources/config/adminRouting.yml"
    prefix:   /backend/admin/reserva
    

hotel:
    resource: "@HotelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group