hotel_bundle_usuari:
    resource: "@HotelBundleUsuariBundle/Resources/config/routing.yml"
    prefix:   /usuari

hotel_bundle_tasca:
    resource: "@HotelBundleTascaBundle/Resources/config/routing.yml"
    prefix:   /tasca

hotel_bundle_admin:
    resource: "@HotelBundleAdminBundle/Resources/config/routing.yml"
    prefix:   /backend/admin

hotel_bundle_reserva:
    resource: "@HotelBundleReservaBundle/Resources/config/routing.yml"
    prefix:   /reserva

hotel:
    resource: "@HotelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group