<?php

namespace HotelBundle\Repository;

use HotelBundle\Entity\Client;
/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

	public function retornaClient($container){
	    $usuari =  $container->get('security.token_storage')->getToken()->getUser();

	    $client = new Client();

	    if($usuari == "anon."){
	      $client->setNom(null);
	    }else{
	      $em->getEntityManager();
	      $client = $em->getRepository('HotelBundle:Client')->findOneByUser($usuari->getId());
	    }

	    return $client;
 	} 	

}
