<?php

namespace HotelBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

use Doctrine\ORM\EntityRepository;

use HotelBundle\Entity\Comanda;
use HotelBundle\Entity\Reserva;
/**
 * ComandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComandaRepository extends \Doctrine\ORM\EntityRepository
{

	public function calcularPreu(Request $request, $comanda){
        $session = $request->getSession();
        $modalitat = 0;
        $habitacions = 0;
        $total = 0;

        $totalModalitat = 0;
        $totalHabitacions = 0;

    	$em = $this->getEntityManager();

        if($comanda->getId() == null ){
            $reserva =$session->get('arrayReserva');
            foreach ($reserva as $value) {
                $modalitat =  $value->getModalitat()->getPreu();
                $places = $value->getHabitacio()->getPlaces();
                $habitacions = $value->getHabitacio()->getPreu();

                $totalModalitat += ($modalitat * $places);

                $totalHabitacions += $habitacions;
            }
        }else{
            $reserva =$em->getRepository('HotelBundle:Reserva')->findBy(array('comanda' => $comanda->getId()));
            foreach ($reserva as $value) {
              $modalitat =$value->getModalitat()->getPreu();
              $places = $value->getHabitacio()->getPlaces();
              $habitacions =  $value->getHabitacio()->getPreu();

              $totalModalitat += ($modalitat * $places);
              $totalHabitacions += $habitacions;
            }
        }  
        $total = $totalModalitat + $totalHabitacions;

    return array($totalModalitat,$totalHabitacions,$total);  
    }
	

}
