<?php

namespace HotelBundle\Repository;

/**
 * EstatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatRepository extends \Doctrine\ORM\EntityRepository
{
}
