<?php

namespace HotelBundle\Repository;

	/**
	 * HabitacioRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class HabitacioRepository extends \Doctrine\ORM\EntityRepository
	{

		public function getHabitacionsByDate($dataInici, $dataFi){
		  $em = $this->getEntityManager();
		  $query = $em->createQuery(
		  	'SELECT h From HotelBundle:Habitacio h
			 WHERE h not in (
			 	SELECT IDENTITY(r.habitacio)
				FROM HotelBundle:Reserva r
			 	INNER JOIN r.comanda c WITH r.comanda=c.id 
			 	WHERE c.dataEntrada >= :dataInici and c.dataSortida <= :dataFi ) 
			 	ORDER BY h.preu ASC'
		    )->setParameter('dataInici', $dataInici->format('Y-m-d'))->setParameter('dataFi', $dataFi->format('Y-m-d'));

		  return $query->getResult();
		}
	}