<?php

namespace HotelBundle\Repository;

	/**
	 * HabitacioRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class HabitacioRepository extends \Doctrine\ORM\EntityRepository
	{

		public function getHabitacionsByDate(Request $request, $dataInici, $dataFi){
		  $em = $this->getDoctrine()->getManager();
		  $query = $em->createQuery(
		    'SELECT h 
			from HotelBundle:Habitacio h
			INNER JOIN h.reserva r WITH r.habitacio = h.id
			INNER JOIN r.comanda c WITH r.comanda = c.id
		    WHERE c.dataInici >= :dataInici and c.dataFi <= :dataFi
		    ORDER BY p.preu ASC'
		    )->setParameter('dataInici', $dataInici)->setParameter('dataFi', $dataFi);

		  return $query->getResult();
		}
	}