<?php

namespace HotelBundle\Repository;

/**
 * HabitacioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitacioRepository extends \Doctrine\ORM\EntityRepository
{
}
