<?php

namespace HotelBundle\Repository;

/**
 * ModalitatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalitatRepository extends \Doctrine\ORM\EntityRepository
{
}
