<?php

namespace HotelBundle\Repository;

	use HotelBundle\Entity\Treballador;
	/**
	 * TascaRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class TascaRepository extends \Doctrine\ORM\EntityRepository{


		 public function getTasquesByTreballadorType($treballador){

	      $em = $this->getEntityManager();
	      $query = $em->createQuery(
	      'SELECT p
			FROM HotelBundle:Treball p 
				INNER join p.tasca t WITH p.tasca = t.id 
				INNER join t.tipusTasca r WITH t.tipusTasca = r.id 
				INNER join r.tipusTreballador d WITH r.tipusTreballador = d.id 
			WHERE p.estat = 1 and d.id=:treb' 
			)->setParameter('treb', $treballador->getTipusTreballador()->getId());

	      return  $query->getResult();
	    
	    }
	}
