	<?php

	namespace HotelBundle\Repository;

	/**
	 * TascaRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class TascaRepository extends \Doctrine\ORM\EntityRepository{


		 public function getTasquesByTreballadorType($treballador){

	      $em = $this->getEntityManager();
	      $query = $em->createQuery(
	      'SELECT p
	      FROM HotelBundle:Tasca p
	      INNER join p.tipusTasca r with p.tipusTasca=r.id
	      Inner join r.tipusTreballador d with r.tipusTreballador=d.id
	      WHERE p.estat = 1 and d.id=:treb'
	      )->setParameter('treb', $treballador->getTipusTreballador()->getId());

	      return  $query->getResult();
	    
	    }
	}
