<?php

namespace HotelBundle\Repository;

/**
 * TipusTreballadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusTreballadorRepository extends \Doctrine\ORM\EntityRepository
{
}
