<?php

namespace HotelBundle\Repository;

/**
 * TipusHabitacioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusHabitacioRepository extends \Doctrine\ORM\EntityRepository
{
}
