<?php

namespace HotelBundle\Repository;

/**
 * TipusTascaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipusTascaRepository extends \Doctrine\ORM\EntityRepository
{
}
