<?php

namespace HotelBundle\Repository;

/**
 * TreballadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreballadorRepository extends \Doctrine\ORM\EntityRepository
{
}
