<?php

namespace HotelBundle\Repository;

/**
 * TreballRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreballRepository extends \Doctrine\ORM\EntityRepository
{
}
