#Client
hotel_bundle_admin_reserva_llistaClient:
    path:     /llistaClient/
    defaults: { _controller: HotelBundleReservaBundle:Client:index }

hotel_bundle_admin_reserva_afegirClient:
    path:     /afegirClient/
    defaults: { _controller: HotelBundleReservaBundle:Client:afegirClient }

hotel_bundle_admin_reserva_editarClient:
    path:     /editarClient/{id}
    defaults: { _controller: HotelBundleReservaBundle:Client:editarClient }

hotel_bundle_admin_reserva_eliminarClient:
    path:     /eliminarClient/{id}
    defaults: { _controller: HotelBundleReservaBundle:Client:eliminarClient }