hotel_bundle_reserva_homepage:
    path:     /
    defaults: { _controller: HotelBundleReservaBundle:Comanda:buscarReserva }

hotel_bundle_reserva_buscaComanda:
    path:     /buscarReserva/{id}
    defaults: { _controller: HotelBundleReservaBundle:Comanda:buscarReserva }

hotel_bundle_reserva_editarLineaComanda:
    path:     /editarLineaComanda/{id}
    defaults: { _controller: HotelBundleReservaBundle:Comanda:editarLinea }

hotel_bundle_reserva_editarComanda:
    path:     /editarReserva/{id}
    defaults: { _controller: HotelBundleReservaBundle:Comanda:editarComanda }

hotel_bundle_reserva_editarClient:
    path:     /editarClient/{id}
    defaults: { _controller: HotelBundleReservaBundle:Client:editarClient }

hotel_bundle_reserva_llistaHabitacionsFrontend:
    path:     /habitacions
    defaults: { _controller: HotelBundleReservaBundle:LlistaHabitacions:index}